% DESCRIPTION: Orchestrator for Stage 02 — Conflict detection.
%              Initializes the VISSIM COM connection, imports network data,
%              builds link and signal head adjacency lists, and computes the
%              topological conflict matrices (crossing and convergence).
% AUTHOR: Sergio Rojas-Blanco | sergio.rojas@uca.es | University of Cádiz
% LICENSE: GNU GPLv3

%% 0: Connection to Vissim
feature('COM_SafeArraySingleDim', 1);
Vissim = actxserver('Vissim.Vissim');
[networkName, networkPath] = uigetfile('*.inpx');
Vissim.LoadNet(fullfile(networkPath, networkName), false);

%% 1. Network data extraction (static infrastructure)
% Import link geometry, signal head positions, and topology from VISSIM COM
Import_network_data;

%% 2. Topological processing and analytical variables

% --- Geometric tolerances for graph navigation ---
Connection_Tolerance = 1.0;   % [m] margin for connector proximity to signal head shadow
Parallel_Tolerance   = 0.5;   % [m] margin for grouping co-located (parallel) signal heads

% --- Link-level adjacency list ---
% Build the directed link graph: for each link, identify downstream
% neighbours (connectors and their target links) with connection points.
[AdjacencyListOfLinks, ConnectionPointOfAdjacent] = Adjacency_list_of_links( ...
    LinksData.NoOfLinks, ...
    LinksData.FromLinkOfLinks, ...
    LinksData.ToLinkOfLinks, ...
    LinksData.FromPosOfLinks, ...
    LinksData.ToPosOfLinks);

% --- Mean traffic speed for ETA computation ---
MeanSpeedKmh = 40; % [km/h] average urban traffic speed (adjustable per scenario)

% --- Topological conflict detection ---
% Compute crossing and convergence conflicts between signal head groups.
% Returns per-signal-head conflict lists, distances, and ETAs to each
% crossing conflict point.
[SignalHeadsConflictList, SignalHeadsConflictDistances, SignalHeadsConflictETAs] = ...
    Conflict_list_of_signal_heads( ...
        AdjacencyListOfLinks, ...
        LinksData.NoOfLinks, ...
        SignalHeadsData.LinkOfSignalHeads, ...
        SignalHeadsData.NoOfSignalHeads, ...
        SignalHeadsData.PosOfSignalHeads, ...
        SignalHeadsData.SignalHeadsOfLinks, ...
        LinksData.Length2DOfLinks, ...
        LinksData.CoordsOfLinks, ...
        LinksData.FromLinkOfLinks, ...
        LinksData.ToLinkOfLinks, ...
        LinksData.IsConnOfLinks, ...
        LinksData.FromPosOfLinks, ...
        LinksData.ToPosOfLinks, ...
        ConnectionPointOfAdjacent, ...
        Connection_Tolerance, ...
        Parallel_Tolerance, ...
        MeanSpeedKmh);

fprintf('Conflict detection complete (SignalHeadsConflictList, SignalHeadsConflictDistances, SignalHeadsConflictETAs): %d signal heads, %d conflict entries.\n', ...
    numel(SignalHeadsData.NoOfSignalHeads), ...
    sum(cellfun(@numel, SignalHeadsConflictList)));
