% DESCRIPTION: Orchestrator for Stage 01 — Adjacency computation.
%              Sequentially imports the VISSIM network data, builds the
%              link-level adjacency list, and then builds the signal-head-
%              level adjacency list with traversal distances.
% AUTHOR: Sergio Rojas-Blanco | sergio.rojas@uca.es | University of Cádiz
% LICENSE: GNU GPLv3

% Step 0: Connection to Vissim
feature('COM_SafeArraySingleDim', 1);
Vissim = actxserver('Vissim.Vissim');
[networkName, networkPath] = uigetfile('*.inpx');
Vissim.LoadNet(fullfile(networkPath, networkName), false);

% Step 1: Import network topology and signal head data from VISSIM COM
Import_network_data;

% Step 2: Build link-level adjacency list
[AdjacencyListOfLinks, ConnectionPointOfAdjacent] = Adjacency_list_of_links( ...
    LinksData.NoOfLinks, ...
    LinksData.FromLinkOfLinks, ...
    LinksData.ToLinkOfLinks, ...
    LinksData.FromPosOfLinks, ...
    LinksData.ToPosOfLinks);

% Step 3: Build signal-head-level adjacency list via BFS
Parallel_Tolerance = 0.5;   % [m] tolerance for co-located (parallel) signal heads
Connection_Tolerance = 0.5;   % [m] tolerance for connector proximity to signal head shadow

[AdjacencyListOfSignalHeads, DistancesToAdjacentSignalHeads] = Adjacency_list_of_real_signal_heads( ...
    LinksData.NoOfLinks, ...
    SignalHeadsData.NoOfSignalHeads, ...
    SignalHeadsData.LinkOfSignalHeads, ...
    SignalHeadsData.SignalHeadsOfLinks, ...
    LinksData.FromLinkOfLinks, ...
    LinksData.ToLinkOfLinks, ...
    LinksData.IsConnOfLinks, ...
    LinksData.FromPosOfLinks, ...
    LinksData.ToPosOfLinks, ...
    SignalHeadsData.PosOfSignalHeads, ...
    LinksData.Length2DOfLinks, ...
    Parallel_Tolerance, ...
    Connection_Tolerance);

fprintf('Adjacency list computed (AdjacencyListOfSignalHeads and DistancesToAdjacentSignalHeads): %d links, %d signal heads processed.\n', ...
    numel(LinksData.NoOfLinks), numel(SignalHeadsData.NoOfSignalHeads));
